<style type="text/css" data-type="vc_shortcodes-custom-css">.vc_custom_1513922206821{margin-top: 10px !important;}</style><link rel='stylesheet' id='wpa-css-css'  href='https://walisongo.ac.id/wp-content/plugins/wp-attachments/styles/0/wpa.css?ver=5.6.8' media='all' />
<link rel='stylesheet' id='vc_google_fonts_montserratregular700-css'  href='//fonts.googleapis.com/css?family=Montserrat%3Aregular%2C700&#038;ver=5.6.8' media='all' />
<div class="vc_grid vc_row vc_grid-gutter-35px vc_pageable-wrapper vc_hook_hover" data-vc-pageable-content="true"><div class="vc_pageable-slide-wrapper vc_clearfix" data-vc-grid-content="true"><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-bottom"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-animated-block "><div class="vc_gitem-zone vc_gitem-zone-a vc-gitem-zone-height-mode-auto vc-gitem-zone-height-mode-auto-16-9" style="background-image: url('https://walisongo.ac.id/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-20-at-15.47.48-1024x768.jpeg') !important;">
		<img src="https://walisongo.ac.id/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-20-at-15.47.48-1024x768.jpeg" class="vc_gitem-zone-img" alt="">	<div class="vc_gitem-zone-mini">
			</div>
</div>
</div>
<div class="vc_gitem-zone vc_gitem-zone-c vc_custom_1513922206821">
	<div class="vc_gitem-zone-mini">
		<div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-"><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="font-size: 18px;text-align: center;font-family:Montserrat;font-weight:700;font-style:normal" ><a href="https://walisongo.ac.id/?p=10000000012250" class="vc_gitem-link" title="UIN Walisongo dan BPJS Ketenagakerjaan Penjajakan Kerjasama, Siap Lindungi Mahasiswa Praktek">UIN Walisongo dan BPJS Ketenagakerjaan Penjajakan Kerjasama, Siap Lindungi Mahasiswa Praktek</a></div></div><div class="vc_separator wpb_content_element vc_separator_align_center vc_sep_width_20 vc_sep_border_width_4 vc_sep_pos_align_center vc_separator_no_text vc_sep_color_black" ><span class="vc_sep_holder vc_sep_holder_l"><span  class="vc_sep_line"></span></span><span class="vc_sep_holder vc_sep_holder_r"><span  class="vc_sep_line"></span></span>
</div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><div style="font-size: 13px;text-align: justify;font-family:Montserrat;font-weight:400;font-style:normal" ><p>UIN Walisongo Online, Semarang &#8211; Universitas Islam Negeri Walisongo mengadakan Audiensi dengan BPJS Ketenagakerjaan Kota Semarang dalam rangka Koordinasi penjajakan kerjasama perlindungan kecelakaan kerja bagi mahasiswa dalam praktek kuliah lapangan. Kegiatan berlangsung di Ruang Rapat Rektorat lantai 3 pada Selasa (20/2/2024). Audiensi diikuti oleh perwakilan dari Bagian Perencanaan Keuangan Universitas,<span class="excerpt-hellip"> […]</span></p>
</div></div><div class="vc_btn3-container vc_btn3-inline" ><a href="https://walisongo.ac.id/?p=10000000012250" class="vc_gitem-link vc_general vc_btn3 vc_btn3-size-xs vc_btn3-shape-rounded vc_btn3-style-flat vc_btn3-color-success" title="Baca Selengkapnya"  >Baca Selengkapnya</a></div>
</div></div>	</div>
</div>
</div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-bottom"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-animated-block "><div class="vc_gitem-zone vc_gitem-zone-a vc-gitem-zone-height-mode-auto vc-gitem-zone-height-mode-auto-16-9" style="background-image: url('https://walisongo.ac.id/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-16-at-15.22.16-1024x682.jpeg') !important;">
		<img src="https://walisongo.ac.id/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-16-at-15.22.16-1024x682.jpeg" class="vc_gitem-zone-img" alt="">	<div class="vc_gitem-zone-mini">
			</div>
</div>
</div>
<div class="vc_gitem-zone vc_gitem-zone-c vc_custom_1513922206821">
	<div class="vc_gitem-zone-mini">
		<div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-"><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="font-size: 18px;text-align: center;font-family:Montserrat;font-weight:700;font-style:normal" ><a href="https://walisongo.ac.id/?p=10000000012247" class="vc_gitem-link" title="UIN Walisongo Adakan Sosialisasi Penerimaan Mahasiswa Baru 2024 ke Guru Bimbingan Konseling">UIN Walisongo Adakan Sosialisasi Penerimaan Mahasiswa Baru 2024 ke Guru Bimbingan Konseling</a></div></div><div class="vc_separator wpb_content_element vc_separator_align_center vc_sep_width_20 vc_sep_border_width_4 vc_sep_pos_align_center vc_separator_no_text vc_sep_color_black" ><span class="vc_sep_holder vc_sep_holder_l"><span  class="vc_sep_line"></span></span><span class="vc_sep_holder vc_sep_holder_r"><span  class="vc_sep_line"></span></span>
</div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><div style="font-size: 13px;text-align: justify;font-family:Montserrat;font-weight:400;font-style:normal" ><p>UIN Walisongo Online, Semarang – Universitas Islam Negeri (UIN) Walisongo mengadakan Sosialisasi dan Pelatihan Perencanaan Orientasi Studi Lanjut Siswa Bagi Para Guru Bimbingan Konselor SMA/MA/SMK/ Sederajat Se- Provinsi Jawa Tengah. Kegiatan dilaksanakan pada Jum’at (16/2/2024) di Teater Lantai 4 Gedung K.H.Soleh Darat. Sosialisasi dilaksanakan secara blanded, sebanyak 75 Guru Bimbingan<span class="excerpt-hellip"> […]</span></p>
</div></div><div class="vc_btn3-container vc_btn3-inline" ><a href="https://walisongo.ac.id/?p=10000000012247" class="vc_gitem-link vc_general vc_btn3 vc_btn3-size-xs vc_btn3-shape-rounded vc_btn3-style-flat vc_btn3-color-success" title="Baca Selengkapnya"  >Baca Selengkapnya</a></div>
</div></div>	</div>
</div>
</div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-bottom"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-animated-block "><div class="vc_gitem-zone vc_gitem-zone-a vc-gitem-zone-height-mode-auto vc-gitem-zone-height-mode-auto-16-9" style="background-image: url('https://walisongo.ac.id/wp-content/uploads/2024/02/IMG_9716-1024x683.jpg') !important;">
		<img src="https://walisongo.ac.id/wp-content/uploads/2024/02/IMG_9716-1024x683.jpg" class="vc_gitem-zone-img" alt="">	<div class="vc_gitem-zone-mini">
			</div>
</div>
</div>
<div class="vc_gitem-zone vc_gitem-zone-c vc_custom_1513922206821">
	<div class="vc_gitem-zone-mini">
		<div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-"><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="font-size: 18px;text-align: center;font-family:Montserrat;font-weight:700;font-style:normal" ><a href="https://walisongo.ac.id/?p=10000000012242" class="vc_gitem-link" title="Jelang Seminggu Menuju Pemilu, Rheyna Wisudawan Terbaik UIN Walisongo Ajak Gunakan Hak Pilih ">Jelang Seminggu Menuju Pemilu, Rheyna Wisudawan Terbaik UIN Walisongo Ajak Gunakan Hak Pilih </a></div></div><div class="vc_separator wpb_content_element vc_separator_align_center vc_sep_width_20 vc_sep_border_width_4 vc_sep_pos_align_center vc_separator_no_text vc_sep_color_black" ><span class="vc_sep_holder vc_sep_holder_l"><span  class="vc_sep_line"></span></span><span class="vc_sep_holder vc_sep_holder_r"><span  class="vc_sep_line"></span></span>
</div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><div style="font-size: 13px;text-align: justify;font-family:Montserrat;font-weight:400;font-style:normal" ><p>UIN Walisongo Online, Semarang- Universitas Islam Negeri(UIN) Walisongo Semarang melaksanakan prosesi wisuda Periode Februari 2024. Wisuda kali ini merupakan wisuda Doktor (S.3) Ke-34, Magister (S.2) ke 58 dan Sarjana (S.1) ke-91 dilaksanakan pada Rabu(7/2/2024) di Gedung Tgk.Ismail Yaqub dengan jumlah wisudawan sebanyak 1085 orang. Wisudawan terdiri dari 10 orang Doktor,<span class="excerpt-hellip"> […]</span></p>
</div></div><div class="vc_btn3-container vc_btn3-inline" ><a href="https://walisongo.ac.id/?p=10000000012242" class="vc_gitem-link vc_general vc_btn3 vc_btn3-size-xs vc_btn3-shape-rounded vc_btn3-style-flat vc_btn3-color-success" title="Baca Selengkapnya"  >Baca Selengkapnya</a></div>
</div></div>	</div>
</div>
</div><div class="vc_clearfix"></div></div></div></div>